### ISSUE TITLE
Missing release for version 1.5.0

### ISSUE THREAD

**Issue by cowwoc** [qos-ch/logback-access#1]
Hi,

Logback version 1.5.0 has been released, but the logback-access artifact remains at version 1.4.8. Was this intentional?

**Comment by ceki** [comment]
Hi @cowwoc,  

Thank  you for your inquiry. The 1.5.x series is a direct descendant of and a drop-in replacement for the 1.4.x series. It differs from the 1.4.x series by the relocation of the logback-access module which was moved to its own separate[ github repository](https://github.com/qos-ch/logback-access).

**Comment by cowwoc** [comment]
Got it. So when upgrading to version 1.5.0 I should remove this dependency altogether. Is that correct?

**Comment by ceki** [comment]
@cowwoc Logback-access is usually installed with/into the servlet container. The response to your question depends on your set up.

**Comment by cowwoc** [comment]
Ah, got it. Thanks for the clarification.
