### ISSUE TITLE
Make RequestWrapper constructor public

### ISSUE THREAD

**Issue by croudet** [qos-ch/logback-access#12]
Would it be possible to make [jetty12/src/main/java/ch/qos/logback/access/jetty/RequestWrapper.java](https://github.com/qos-ch/logback-access/blob/40fada85146ecf1bf3cc89f8997b7fd27a02b3e8/jetty12/src/main/java/ch/qos/logback/access/jetty/RequestWrapper.java#L44) constructor public so we can reuse that class in [logbacc-access-spring-boot-starter](https://github.com/akkinoc/logback-access-spring-boot-starter/pull/407)

**Comment by ceki** [comment]
Fixed in commit d26878c49c74b809

**Comment by ceki** [comment]
Fixed in logback-access version 2.0.2 which was released on 2024-07-08.
