### ISSUE TITLE
Logback-access 2.0.1 does not work using included resources for Tomcat access logs

### ISSUE THREAD

**Issue by RobbanHoglund** [qos-ch/logback-access#14]
Logback 1.5.6 does not work using included resources for Tomcat access logs

From startup.

11:19:28,784 |-INFO in ch.qos.logback.access.tomcat.LogbackValve[null] - Found [logback-access.xml] as a resource.
11:19:28,795 |-INFO in ch.qos.logback.access.common.model.processor.ConfigurationModelHandler - debug attribute not set
11:19:28,795 |-INFO in ch.qos.logback.core.joran.util.ConfigurationWatchListUtil@78a287ed - Adding [jar:file:/C:/Users/p950rhw/.gradle/caches/modules-2/files-2.1/org.springframework.boot/spring-boot/3.3.0/83d42f81f312d71b9425f58d1d3f9e8970e51b22/spring-boot-3.3.0.jar!/org/springframework/boot/logging/logback/defaults.xml] to configuration watch list.
11:19:28,795 |-INFO in ch.qos.logback.core.joran.spi.ConfigurationWatchList@7b4619a3 - URL [jar:file:/C:/Users/p950rhw/.gradle/caches/modules-2/files-2.1/org.springframework.boot/spring-boot/3.3.0/83d42f81f312d71b9425f58d1d3f9e8970e51b22/spring-boot-3.3.0.jar!/org/springframework/boot/logging/logback/defaults.xml] is not of type file
11:19:28,799 |-ERROR in ch.qos.logback.core.model.processor.IncludeModelHandler - null configurator supplier. Abandoning inclusion of [org/springframework/boot/logging/logback/defaults.xml]
11:19:28,799 |-INFO in ch.qos.logback.core.joran.util.ConfigurationWatchListUtil@78a287ed - Adding [file:/C:/ws/git/lib-logging/bin/main/andromeda-access-console-appender.xml] to configuration watch list.
11:19:28,801 |-ERROR in ch.qos.logback.core.model.processor.IncludeModelHandler - null configurator supplier. Abandoning inclusion of [andromeda-access-console-appender.xml]
11:19:28,801 |-INFO in ch.qos.logback.core.joran.util.ConfigurationWatchListUtil@78a287ed - Adding [file:/C:/ws/git/lib-logging/bin/main/andromeda-access-observability-appender.xml] to configuration watch list.
11:19:28,803 |-ERROR in ch.qos.logback.core.model.processor.IncludeModelHandler - null configurator supplier. Abandoning inclusion of [andromeda-access-observability-appender.xml]
11:19:28,803 |-INFO in ch.qos.logback.core.joran.util.ConfigurationWatchListUtil@78a287ed - Adding [file:/C:/ws/git/lib-logging/bin/main/andromeda-access-logread-appender.xml] to configuration watch list.
11:19:28,806 |-ERROR in ch.qos.logback.core.model.processor.IncludeModelHandler - null configurator supplier. Abandoning inclusion of [andromeda-access-logread-appender.xml]
11:19:28,806 |-INFO in ch.qos.logback.core.model.processor.DefaultProcessor@9d3a7a1 - End of configuration.
11:19:28,806 |-INFO in ch.qos.logback.access.common.joran.JoranConfigurator@1c411474 - Registering current configuration as safe fallback point

![image](https://github.com/qos-ch/logback/assets/6659114/63a18443-8b9e-4643-a414-46c0d48bb534)

The configuration supplier ends up being null. 

This works fine with Spring boot 3.2.5 and logback 1.4.14 with but not with Spring boot 3.3.0 and logback 1.5.6

**Comment by dskeppstedt** [comment]
Hi, @ceki  have the same issue, is it possible to get a snapshot version to verify the fix?

**Comment by RobbanHoglund** [comment]
Thanks for a quick fix of this issue, when is 2.0.2 planned to be released?

**Comment by dskeppstedt** [comment]
any update on this?

**Comment by runeflobakk** [comment]
I have tested this with a Spring Boot 3.3.1 application running on Jetty 12. The issue exists with Jetty as well, and I can confirm that the commit https://github.com/qos-ch/logback-access/commit/c9447c53b5919d8 fixes it for Jetty as well 👍 

It also works together with the [Support for logback-access 2.0.0 PR](https://github.com/logfellow/logstash-logback-encoder/pull/1015) for logstash-logback-encoder (yet to be merged)

**Comment by ceki** [comment]
Fixed in logback-access version 2.0.2 which was released on 2024-07-08.
