### ISSUE TITLE
Add locale option to access log DateConverter

### ISSUE THREAD

**Issue by at055612** [qos-ch/logback-access#18]
`ch.qos.logback.classic.pattern.DateConverter` (https://github.com/qos-ch/logback/blob/master/logback-classic/src/main/java/ch/qos/logback/classic/pattern/DateConverter.java) has

```java
        List<String> optionList = getOptionList();
        ZoneId zoneId = null;
        // if the option list contains a TZ option, then set it.
        if (optionList != null && optionList.size() > 1) {
            String zoneIdString = (String) optionList.get(1);
            zoneId = ZoneId.of(zoneIdString);
            addInfo("Setting zoneId to \""+zoneId+"\"");
        }

        Locale locale = null;
        if (optionList != null && optionList.size() > 2) {
            String localeIdStr = (String) optionList.get(2);
            locale = Locale.forLanguageTag(localeIdStr);
            addInfo("Setting locale to \""+locale+"\"");
        }
        try {
            // if zoneId is null, the CachingDateFormatter will use the ZoneId.systemDefault()
            cachingDateFormatter = new CachingDateFormatter(datePattern, zoneId, locale);
```

while `ch.qos.logback.access.common.pattern.DateConverter` (https://github.com/qos-ch/logback-access/blob/main/common/src/main/java/ch/qos/logback/access/common/pattern/DateConverter.java) used for access logs has only

```java
        ZoneId zoneId = null;
        List<String> optionList = getOptionList();

        // if the option list contains a TZ option, then set it.
        if (optionList != null && optionList.size() > 1) {
            String zoneIdString = (String) optionList.get(1);
            zoneId = ZoneId.of(zoneIdString);
        }

        try {
            cachingDateFormatter = new CachingDateFormatter(datePattern, zoneId);
```

It would be useful to be able to specify the locale in access log date/time formats.  This looks like a simple change to just add in

```java
        Locale locale = null;
        if (optionList != null && optionList.size() > 2) {
            String localeIdStr = (String) optionList.get(2);
            locale = Locale.forLanguageTag(localeIdStr);
            addInfo("Setting locale to \""+locale+"\"");
        }
```

then add `locale` as the third arg to `new CachingDateFormatter(datePattern, zoneId, locale)`.

The reason for requesting this is that JDK17 introduced a change (https://bugs.openjdk.org/browse/JDK-8256837) to the en_GB locale which changes the abbreviated month from `Sept` to `Sep` when using `MMM`.  This is particularly relevant for access logs that use a pattern like `dd/MMM/yyyy:HH:mm:ss Z`.  With the code as it is we have no way to change the locale (to something else, like `en`) if we want our logs to remain consistent with `Sep`.  We could then do something like `%t{dd/MMM/yyyy:HH:mm:ss Z,UTC,en}`.

It would also seem sensible to replicate this change (https://github.com/qos-ch/logback/commit/1b7fe9498d491e367da698bc921323bb11dd4120) in the access log DateConverter so they both support `STRICT`.

Happy to raise a PR for this change if you think it is warranted.

**Comment by ceki** [comment]
@at055612 Yes please.

**Comment by at055612** [comment]
Thanks for merging @ceki
