### ISSUE TITLE
Versions file or changelog missing

### ISSUE THREAD

**Issue by yachtintheband** [qos-ch/logback-access#2]
I cannot find this in mvn central and I do not see a version file or changelog. Not sure if I should use the version in the pom or not.

**Comment by ceki** [comment]
logback-access from its own repo was not yet published.

**Comment by yachtintheband** [comment]
Okay, what are the blockers to that and is there a timeline yet?

**Comment by DorisEckel8412** [comment]
Is there a timeline for the release? We need the Jetty12 support and are waiting for the release now since a while.

**Comment by ceki** [comment]
Logback-access version 2.0.0 was released moments ago.

**Comment by yachtintheband** [comment]
Not trying to be difficult, just looking for clarity. 

You said [here](https://github.com/qos-ch/logback/issues/719#issuecomment-2018177271) that logback access has moved to it's own repo to support jetty 12. Then you say in this thread that this repo has not been released, and then in your latest comment that logback 2.0 is released? So is there already a happy path to use logback access with jetty 12 or not yet?

**Comment by ceki** [comment]
@yachtintheband Please have a look a the [documentation](https://logback.qos.ch/access.html). Do not hesitate to report back if anything is not clear.
