### ISSUE TITLE
Modified the approach for configuring the requestURI in AccessEvent

### ISSUE THREAD

**Issue by sondemar** [qos-ch/logback-access#4]
Before migration the logback-access module to a separate repository the [getRequestURI() ](https://github.com/qos-ch/logback/blob/407f935603f3f4d7825e4f57f85ed494da3b7197/logback-access/src/main/java/ch/qos/logback/access/spi/AccessEvent.java#L161) generated "a string containing the part of the URL from the protocol name up to the query string" (please refer to the official [documentation](https://jakarta.ee/specifications/platform/8/apidocs/?javax/servlet/http/HttpServletRequest.html)).

Currently, it [produces](https://github.com/qos-ch/logback-access/blob/c39c35410b06e0b990ecf4d18629ae06f0395515/common/src/main/java/ch/qos/logback/access/common/spi/AccessEvent.java#L156) an URL with a scheme and host, which affects the result of generated `url` attribute in access logs.

**Comment by ceki** [comment]
@sondemar Hello,

In which servlet container are you observing this? Jetty or Tomcat? And which version?

**Comment by sondemar** [comment]
> @sondemar Hello,
> 
> In which servlet container are you observing this? Jetty or Tomcat? And which version?

Hi.
I have only verified with Jetty.
version 1.14.1:
![Screenshot 2024-04-02 at 14 02 59](https://github.com/qos-ch/logback-access/assets/7047919/4dc94b55-e03d-4780-95b2-29dfba6c0627)


version 2.0.0:
![Screenshot 2024-04-02 at 14 05 24](https://github.com/qos-ch/logback-access/assets/7047919/5b47f344-4765-40c4-8690-d127fda31cd3)

**Comment by ceki** [comment]
When you say version 1.14.1, what component are you referring to? Same for version 2.0.0. Version 2.0.0 of what?

**Comment by sondemar** [comment]
> @sondemar In which version of Jetty?

Jetty 12. I have created a possible change https://github.com/qos-ch/logback-access/pull/5

**Comment by ceki** [comment]
@sondemar  Thank you for PR #5. Unfortunately, it fails the [DCO check.](https://github.com/qos-ch/logback-access/pull/5/checks?check_run_id=23345310213)

The DCO link provides a way to add the proper sign-off. Please let me know if you run into trouble.

**Comment by sondemar** [comment]
> @sondemar Thank you for PR #5. Unfortunately, it fails the [DCO check.](https://github.com/qos-ch/logback-access/pull/5/checks?check_run_id=23345310213)
> 
> The link to the DCO check provides a way to add the proper sign-off. Please let me know if you run into trouble.

@ceki , now it should be fine

**Comment by marinedayo** [comment]
@ceki @sondemar Thank you for releasing Logback Access 2.0.1.

I've promptly upgraded to 2.0.1 and noticed a change in behavior regarding the handling of the `%requestURI` word in access logs when using Jetty 12.
Specifically, the paths are now URL-decoded before being logged. This behavior is different from what is observed in Tomcat environments or when using Logback Access 1.4.x, where the paths are logged in their percent-encoded form.

For example, when accessing `http://localhost:8080/<test>`:

- Jetty 12 - `/<test>`
- Tomcat or Logback Access 1.4.x - `/%3Ctest%3E`

Could you share any background on your decision to use `HttpURI::getDecodedPath`?

- https://github.com/qos-ch/logback-access/pull/5

I believe keeping the paths encoded might be better when ensuring log data consistency across different environments or with previous versions.
So I would suggest using [`HttpURI::getPath`](https://eclipse.dev/jetty/javadoc/jetty-12/org/eclipse/jetty/http/HttpURI.html) instead.

**Comment by sondemar** [comment]
> I believe keeping the paths encoded might be better when ensuring log data consistency across different environments or with previous versions. So I would suggest using [`HttpURI::getPath`](https://eclipse.dev/jetty/javadoc/jetty-12/org/eclipse/jetty/http/HttpURI.html) instead.

This is a reasonable explanation. 👍
